# Generated by Selenium IDE
from random import random, randrange
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
# import utils.set_site as set_site
import random

class TestNavigateReport():
    def setup_method(self, method):
        self.driver_path = "C:\\Program Files\\Google\\Chrome\\Application\\chromedriver.exe"
        self.driver = webdriver.Chrome(executable_path=self.driver_path)
        self.driver.maximize_window()
        url = "http://yp.yahshuasupport.com/signin/?login=yes"
        self.driver.get(url)
        # set_site.login(self)
        self.driver.find_element_by_link_text("Reports").click()
        self.driver.find_element_by_link_text("Payslip").click()
  
    def teardown_method(self, method):
        self.driver.quit()

    def test_viewing_employees_payslip(self):
        
        self.driver.implicitly_wait(10)
        payroll_period = self.driver.find_element_by_xpath("//*[@id='page-wrapper']/div[3]/div/div/div/div/div[2]/div[1]/div/div/a/span[3]")
        time.sleep(5)
        payroll_period.click()
        
        count_period = self.driver.find_elements_by_xpath("//li[contains(@id, 'ui-select-choices-row-0-')]")
        count_payroll_period= len(count_period)
        print(count_payroll_period)
        payroll_count = random.randint(0,count_payroll_period)
        print(payroll_count)
        time.sleep(5)
        self.driver.find_elements_by_xpath("//li[contains(@id, 'ui-select-choices-row-0-')]")[payroll_count-1].click()
        time.sleep(5)
       
        employee = self.driver.find_element_by_xpath("//*[@id='page-wrapper']/div[3]/div/div/div/div/div[2]/div[2]/div/div/a")
        employee.click()

        employee = self.driver.find_elements_by_xpath("//*[@id='ui-select-choices-row-1-']/div/div")
        count_employee= len(employee)
        print(count_employee)
        emp_count = random.randint(1,count_employee)
        print(emp_count)
        time.sleep(5)
        self.driver.find_elements_by_xpath("//li[contains(@id , 'ui-select-choices-row-1-')]")[emp_count].click()
        time.sleep(5)

        search_button = self.driver.find_element_by_xpath("//*[@id='page-wrapper']/div[3]/div/div/div/div/div[2]/div[3]/div/button")
        search_button.click()

        time.sleep(25)

        #assert payroll not false
        #assert employee null
        #assert employee payslip is viewable
        # pass
